ROLE_CITIZEN = 0
ROLE_POLICE = 1
ROLE_DOCTOR = 2
ROLE_MAFIA = 3

PHASE_DAY_DISCUSSION = "day_discussion"
PHASE_DAY_VOTE = "day_vote"
PHASE_NIGHT = "night"

PLAYER_COUNT = 8
MAX_DAYS = 20
ROLES = [
    ROLE_MAFIA,
    ROLE_MAFIA,
    ROLE_POLICE,
    ROLE_DOCTOR,
    ROLE_CITIZEN,
    ROLE_CITIZEN,
    ROLE_CITIZEN,
    ROLE_CITIZEN,
]

ACTION_SILENT = 0
ACTION_REVEAL_CITIZEN = 1
ACTION_REVEAL_POLICE = 2
ACTION_REVEAL_DOCTOR = 3
ACTION_REVEAL_MAFIA = 4
ACTION_ACCUSE_START = 5
ACTION_ACCUSE_END = ACTION_ACCUSE_START + (PLAYER_COUNT * 4) - 1
TOTAL_ACTIONS = ACTION_ACCUSE_END + 1

LR = 0.00005
GAMMA = 0.99
EPS_CLIP = 0.2
K_EPOCHS = 4
BATCH_SIZE = 256
ENTROPY_COEF = 0.01
VALUE_LOSS_COEF = 0.5
MAX_GRAD_NORM = 0.5

LOG_DIR = "./logs"
MODEL_DIR = "./models"
